[package]
authors = ["Robert Bamler <robert.bamler@gmail.com>"]
edition = "2018"
name = "compressed_dynamic_word_embeddings"
version = "0.0.1"

[dependencies]
byteorder = "1.3.2"
flate2 = "1.0.13"
num = "0.3.0"
rand = "0.7.2"
static_assertions = "1.1.0"

[dev-dependencies]
constriction = {path = "../../constriction"}
criterion = "0.3"

[[bench]]
harness = false
name = "decompression"
